basics:
  email: career@sancaktar.net
  location:
    city: Aurora
    countryCode: Colorado
  name: Errol A. Sancaktar
  profiles:
  - network: Github
    url: https://github.com/errolsancaktar
    username: errolsancaktar
  - network: Linkedin
    url: https://www.linkedin.com/in/errolsancaktar/
    username: errolsancaktar
  urlname: "Current Resume"
  url: https://errolsancaktar.github.io/resume
meta:
  breaks_before:
    education: true
    certificates: false
    references: false
education:
- area: Bachelor of Arts
  institution: Kent State University
  endDate: '2008'
certificates:
- name: Terraform Associate
  date: '2023'
  url: https://www.credly.com/badges/3658f00d-f021-493b-a231-79b6a1d7c504
- name: Google Professional Cloud Architect
  date: '2021'
  url: https://www.credential.net/d27cd19c-3f1d-46ee-9ec0-e5e7a02b8d3d#gs.21c11h
- name: AWS Certified Solutions Architect
  date: '2018'
  url: https://www.credly.com/badges/c3b40133-809f-424b-8d13-dad2d0d3b73a
- name: Red Hat Certified Systems Administrator
  date: '2014'
- name: CompTIA A+ Certification
  date: '2008'
skills:
- keywords:
  - Google Cloud
  - Amazon AWS
  - Microsoft Azure
  - DevOps
  - Pipeline Architecture
  name: Cloud Technologies
- keywords:
  - Ansible
  - Terraform
  - ArgoCD
  - Pulumi
  name: Infrastructure as Code
- keywords:
  - Python
  - Go
  - C/C++
  - Bash
  name: Languages
- keywords:
  - AWS
  - GCP
  - Azure
  - Docker
  - Kubernetes
  - CI/CD
  name: Platforms
- keywords:
  - Linux
  - FreeBSD
  - MacOS
  - Microsoft
  name: OS
references:
- name: Will Weber
  title: Key Enterprise Architect, Google
  email: wweber@google.com
  phone: '650-499-7793'
- name: Enoch Moeller
  title: Solutions Consultant Manager, Google
  email: moellere@google.com
  phone: '828-238-3713'
- name: Geoff Cardamone
  title: Infrastructure Cloud Consultant, Google Public Sector
  email: cardamone@google.com
  phone: '917-353-2876'
- name: Igor Bondarenko
  title: Chief Technology Officer, SEAM Group
  email: ibondare@gmail.com
  phone: '216-386-8446'
- name: Andrew Martin
  title: Senior Linux System Administrator, MIT Lincoln Laboratory
  email: andrew@getmartin.com
  phone: '603-785-6481'
work:
- highlights:
  - Architected and implemented solutions across AWS, Azure, and GCP, utilizing IAC tools to ensure infrastructure consistency and manageability.
  - Designed and built CI/CD pipelines for infrastructure deployment allowing for standardized deployment procedures.
  - Collaborated with cross-functional teams to gather requirements and translate them into cloud-based solutions that align with business goals.
  - Conducted architecture reviews and provided technical guidance to ensure adherence to best practices and security standards.
  - Worked closely with clients to assess their cloud infrastructure needs, designing and implementing solutions that met their specific business requirements.
  - Created detailed architecture diagrams, documentation, and presentations to communicate design concepts and solutions to technical and non-technical stakeholders.
  - Provided training and mentoring to junior team members, fostering skill development and knowledge sharing within the team.
  name: LucidPoint
  position: Cloud Architect
  startDate: '2023-04-12'
  url: https://www.lucidpoint.io/
- highlights:
  - Worked with technical leads, architects, and partners to deliver successful implementations of cloud infrastructure projects.
  - Implemented as well as refactored infrastructure pipelines, deployment methodologies, and automations.
  - Developed architectural designs, created reference architectures, and performed cloud reviews to implement effective environments following industry best practices.
  - Implemented infrastructure-as-code systems to enhance idempotency and replicability.
  - Worked as a Technical Project Manager on larger scale projects coordinating many engineers ensuring both business and technical requirements were met.
  - Integrated hybrid cloud infrastructures giving customers the ability to use best in breed technologies across clouds while controlling costs.
  - Worked on Google Distributed Cloud Hosted architecture incorporating cloud methodologies with secure, offline data center hardware in IL5 Fedramp environments.
  name: Google
  position: Infrastructure Cloud Consultant
  startDate: '2021-09-01'
  endDate: '2023-03-31'
  url: https://cloud.google.com/
- endDate: '2021-09-01'
  highlights:
  - Created and executed strategies to drive customer adoption and use of AWS services.
  - Performed montly and quarterly business reviews to discuss cloud spend, ongoing projects, and upcoming implementations.
  - Technical SME for customer projects, drove discussions with senior leadership regarding incidents, trade-offs, support, and risk management.
  - Acted as a customer advocate for business and architectural needs within AWS.
  - Resolved large-scale and business-critical issues relating to Kubernetes, ECS, EC2, Red Shift, and networking.
  - Developed strategic long-term plans and technical designs while simplifying customer architectures.
  - Interfaced with sales, partners, and customer technical stakeholders to manage project scope, priorities, deliverables, risks/issues, and timelines for successful customer outcomes.
  name: Amazon Web Services
  position: Technical Account Manager
  startDate: '2019-03-01'
  url: https://aws.amazon.com/
- endDate: '2019-03-01'
  highlights:
  - Responsible for all infrastructure both on-premise and in AWS including Networking and VoIP.
  - Managed systems staff including DBAs, End User Support, and Systems Administrators.
  - Implemented multiple open-source technologies for networking and servers.
  - Created standardized desktop management, including windows imaging procedures.
  - Improved and maintained a custom in-house Warehouse Management System including wireless devices, pick and pack stations, as well as inventory systems/devices.
  - Negotiated beneficial rates for telephony and internet at ECS home office as well as remote sites.
  - Established standardized digital signage solutions for employee engagement and knowledge transfer.
  - Implemented native AWS tools to allow our customer-facing websites to scale with demand more easily.
  - Deployed ansible and terraform to environment allowing for better control of deployments.
  name: ECS Tuning
  position: IT/Cloud Manager
  startDate: '2017-07-01'
  url: https://www.ecstuning.com/
- endDate: '2017-07-01'
  highlights:
  - Responsible for the creation of Information Services “Concierge” position, which acted as the first-line contact for all enterprise service requests. This involved services like virtual machine creation up to full network and systems integrations for our power plant operations software.
  - Implemented Red Hat Cloudforms and Ansible Tower in conjunction with our Concierge process. This will allow our end-users to utilize our service catalog to request cloud resources such as RDS and EC2 without the need to understand the AWS environment.
  - Planned and wrote RFP for the upgrade of our IBM Spectrum Protect backup and disaster recovery environment. This is a multi-year implementation involving the replacement of our current quantum system both on-premise and at our backup data center.
  - Created a cloud center of excellence to focus on our growing presence in AWS and other SaaS applications. Built team from both the server group and client services to support all aspects of cloud architecture.
  name: Kent State University
  position: Director, Infrastructure Engineering
  startDate: '2016-10-01'
  url: https://www.kent.edu/
- endDate: '2016-10-01'
  highlights:
  - Planned and implemented the first of its kind Virtual Desktop Infrastructure (VDI) for the college. This involved utilizing Nutanix hyper-converged server infrastructure as well as thin clients for end-users in a scale-up state-of-the-art learning center. It has successfully assisted over 300 students to complete their coursework in the designed collaborative process.
  - Integration of Single Sign-On across Linux, Windows, and Apple platforms through custom-written scripts and configurations. This has allowed many of the highly specialized scientific systems to integrate with other services available on-premise.
  - Management of multiple computational clusters totaling 100+ nodes ranging from traditional computation to Beowulf design clusters.
  - Migration of physical servers to VMWare Vcenter environment now totaling 120 Virtual Machines
  name: Kent State University
  position: Information Services Team Leader
  startDate: '2015-04-01'
  url: https://www.kent.edu/
- endDate: '2015-04-01'
  highlights:
  - Implemented four-node VMware vCenter environment for college and migrated virtual machines. This allowed the decommissioning of 35 physical servers.
  - Created additional 90 servers on this vCenter environment, maintaining ongoing support and updates.
  - Developed many scripts to automate user permissions, file share creation, active directory user, and computer group management.
  - Progressive promotions starting at IT User Support Analyst to IT Manager
  name: Kent State University
  position: IT Manager, College of Arts and Sciences
  startDate: '2006-06-01'
  url: https://www.kent.edu/
