name: release

on:
  push:
    branches: [ main ]

env:
  RESUME_TARGET: out/errol_sancaktar_resume.pdf

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: 'errolsancaktar/resumy'
          path: 'resumy'
          ref: 'Updates'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install requirements
        run: pip install tox

      - name: Release
        run: cd resumy && tox -e build

      - name: Build resume
        run: cd resume && make

      - name: list
        run: ls -lah && tree ../ && pwd

      - name: resumy
        #run: echo "resumy build -o ${RESUME_TARGET} resume/resume_config.yaml && tree"
        run: cd resumy build -o errol_sancaktar_resume.pdf -f "resume" -w "" resume_config.yaml

      - name: list
        run: ls -lah && tree ../

      # - name: Test 'resumy'
      #   run: which resumy
        
      # - name: Set version as short sha
      #   run: echo "VERSION=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      # - name: Get asset name
      #   run: echo "RESUME_NAME=`basename ${RESUME_TARGET}`" >> $GITHUB_ENV

      # - name: Create release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ env.VERSION }}
      #     release_name: Release ${{ env.VERSION }}
      #     draft: false
      #     prerelease: false

      # - name: Upload pdf
      #   id: upload-release-pdf
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ${{ env.RESUME_TARGET }}
      #     asset_name: ${{ env.RESUME_NAME }}
      #     asset_content_type: application/pdf
